name: EC2 auto deploy

on:
  pull_request:
    branches: [ main ]
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Public IP Install
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          REGION="ap-northeast-1"

          # SSHのセキュリティグループを開放
          aws ec2 authorize-security-group-ingress \
            --region $REGION \
            --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

          # 秘密鍵を保存
          echo "${{ secrets.GIT_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

          # EC2 に SSH ＆ git pull
          ssh -oStrictHostKeyChecking=no \
            ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST_NAME }} \
            -i private_key \
            "cd /var/www/html/プロジェクトディレクトリ && \
             git fetch --prune && \
             git checkout main && \
             git pull origin main"

          # SSH のセキュリティグループを閉じる
          aws ec2 revoke-security-group-ingress \
            --region $REGION \
            --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
